"""Build FUSE client"""
import daos_build

def scons():
    """Execute build"""
    Import('env')

    denv = env.Clone()

    have_hdf5 = True

   #If hdf5 installed build hdf_serialize library
    conf = Configure(denv)
    if not conf.CheckLibWithHeader('hdf5', 'hdf5.h', 'c'):
        have_hdf5 = False
    conf.Finish()

    libraries = ['daos', 'hdf5']

    src = ['hdf_serialize.c']
    if have_hdf5 is True:
        print("Building with hdf5 bindings.")
        hdf_serialize = daos_build.library(denv, 'hdf_serialize', src,
                                           LIBS=libraries)
        denv.Install('$PREFIX/lib64/', hdf_serialize)
    else:
        print("No installed hdf5 detected, not building with hdf5 enabled")
if __name__ == "SCons.Script":
    scons()
